### ISSUE TITLE
PHP User Error – yii\base\ErrorException

### ISSUE THREAD

**Issue by selormonray** [owaisalics/colorboxInventorySystem#1]
``` 
Exception 'yii\base\InvalidArgumentException' with message 'The file or directory to be published does not exist: C:\xampp\htdocs\colorboxInventorySystem/vendor\bower/jquery/dist' 

in C:\xampp\htdocs\colorboxInventorySystem\vendor\yiisoft\yii2\web\AssetManager.php:456
```
This is the error I found after starting the project

**Comment by ows-ali** [comment]
Can you elaborate how did you run the project? After installing project
from Github, follow the guidelines in Getting Started section (please
confirm if you have run 'composer install').

**Comment by selormonray** [comment]
Hello Owais,

I began the installation again and it worked perfectly.

Thank you

Regards,
